- name: This playbook will install, configure & Deploy web pages into ignix
  hosts: all
  become: yes
  tasks: 
   - name: install web nginx web server
     apt: name=nginx state=latest update_cache=yes

   - name: Start he nginx web server
     #service: name=nginx state=started enabled=yes
     command: service nginx start